version: '3.8'

networks:
  restaurante:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: restaurante-mysql
    restart: always
    ports:
      - "4208:3306"
    volumes:
      - "./var/libclea/mysql:/var/lib/mysql"
      - "./base_de_datos:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: restaurante
      MYSQL_USER: administrador
      MYSQL_PASSWORD: 1234
    networks:
      - restaurante

  wordpress:
    image: wordpress:latest
    container_name: restaurante-wordpress
    restart: always
    ports:
      - "4282:80"
    volumes:
      - "./var/www/html:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: administrador
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: restaurante
    depends_on:
      - mysql
    networks:
      - restaurante

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: restaurante-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: administrador
      PMA_PASSWORD: 1234
    networks:
      - restaurante

  extract:
    image: ubuntu:latest
    container_name: extract-uploads
    volumes:
      - "./var/www/html:/var/www/html"
      - "./base_de_datos:/base_de_datos"  # Asegúrate de que el archivo uploads.rar esté aquí
      - "../restaurante:/restaurante"  # Montar la carpeta ../restaurante
    entrypoint: ["sh", "-c", "apt-get update && apt-get install -y unrar && unrar x /base_de_datos/uploads.rar /var/www/html/wp-content/uploads/ && cp -r /restaurante /var/www/html/ && chown -R www-data:www-data /var/www/html/restaurante && chmod -R 755 /var/www/html/restaurante && echo 'Sitio web listo'"]
    networks:
      - restaurante
    depends_on:
      - wordpress
